# Generated by Django 5.1.3 on 2024-12-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='restore',
            field=models.BooleanField(default=False),
        ),
    ]
