# Generated by Django 5.1.3 on 2024-12-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_remove_task_restore'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='restore',
            field=models.BooleanField(default=False),
        ),
    ]
