# Generated by Django 5.1.3 on 2024-12-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_task_restore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='restore',
            field=models.BooleanField(default=True),
        ),
    ]
