# Generated by Django 5.1.3 on 2024-12-24 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_alter_task_restore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='restore',
        ),
    ]
